version: '2'
services:
  dns:
    build: .
    ports:
      - 53:53/tcp
      - 53:53/udp
  nginx:
    image: nginx:1.11
    ports:
      - 80:80
    volumes:
      - ./files/nginx/conf.d:/etc/nginx/conf.d
      - ./files/nginx/html/hello.txt:/var/www/html/hello.txt
